### PR TITLE
NuSpec with a dependency on VS2013's Scaffolder - Fixes #116

### LINKED ISSUE #116: Problem with MvcMailer in Visual Studio Express 2013 installing MvcMail in default Mvc Ap
PM> Install-Package MvcMailer
Attempting to resolve dependency 'T4Scaffolding.Core (≥ 1.0.0)'.
Installing 'T4Scaffolding.Core 1.0.0'.
Successfully installed 'T4Scaffolding.Core 1.0.0'.
Set-DefaultScaffolder : Cannot get an instance of EnvDTE.DTE
At C:\Users\MALCOLM\documents\visual studio 2013\Projects\TestApp\packages\T4Scaffolding.Core.1.0.0\tools\init.ps1:50 char:9
-         Set-DefaultScaffolder -Name CustomTemplate -Scaffolder T4Scaffolding.Cus ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Set-DefaultScaffolder], InvalidOperationException
  - FullyQualifiedErrorId : T4Scaffolding.Cmdlets.SetDefaultScaffolderCmdlet

Set-DefaultScaffolder : Cannot get an instance of EnvDTE.DTE
At C:\Users\MALCOLM\documents\visual studio 2013\Projects\TestApp\packages\T4Scaffolding.Core.1.0.0\tools\init.ps1:51 char:9
-         Set-DefaultScaffolder -Name CustomScaffolder -Scaffolder T4Scaffolding.C ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Set-DefaultScaffolder], InvalidOperationException
  - FullyQualifiedErrorId : T4Scaffolding.Cmdlets.SetDefaultScaffolderCmdlet

Installing 'MvcMailer 4.5'.
Successfully installed 'MvcMailer 4.5'.
Adding 'T4Scaffolding.Core 1.0.0' to TestApp.
Successfully added 'T4Scaffolding.Core 1.0.0' to TestApp.
Adding 'MvcMailer 4.5' to TestApp.
Successfully added 'MvcMailer 4.5' to TestApp.
Set-DefaultScaffolder : Cannot get an instance of EnvDTE.DTE
At C:\Users\MALCOLM\documents\visual studio 2013\Projects\TestApp\packages\MvcMailer.4.5\tools\Install.ps1:23 char:1
- Set-DefaultScaffolder -Name Mailer -Scaffolder $mailerScaffolder -SolutionWide - ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Set-DefaultScaffolder], InvalidOperationException
  - FullyQualifiedErrorId : T4Scaffolding.Cmdlets.SetDefaultScaffolderCmdlet

### PR DESCRIPTION
**Pull request by shanselman**
Fixes #116

Scaffolding in 2013 is changing (and has changed) and won't be
supported. However, there is a vs2013 version of the T4Scaffolder and
this package depends on it.

Good news - This seems to work fine under VS3013 when the IDE is run as
Admin.
Bad news - Because this NuGet will have a dependency on a -pre
(prelease) package, then it becomes prerelease. That means there are TWO
packages. MvcMailer and MvcMailer-vs2013.

http://docs.nuget.org/docs/reference/versioning#Prerelease_Versions

That means, you would install it like this:

install-package MvcMailer-vs2013 -pre

Which in turn brings in the T4 pre dependency.

NOTE: I didn't mess with the rake file OR the publish. A NuPkg will get
make when you run rake as the work happens in CSProj (looks like the
rakefile was never completed to support NuGet?)

NOTE 2: I had to update NuGet.exe to latest.

TODO: You'll want to publish the _new_ package as it's down thing (and
perhaps advertise that it exists by mentioning it in the EXISTING
version's NuGet package as well as in the Readme.md? I added that also,
if that's OK.

### CODE REVIEW

**Comment by smsohan** [comment]
@shanselman thanks for this. I really appreciate it. I've created a new branch for vs2013, please open a PR against that branch. That way we can keep the master as is while release a new version for 2013. Will trigger a build tonight.

**Comment by smsohan** [comment]
Here's the branch
https://github.com/smsohan/MvcMailer/tree/MvcMailer-vs2013

**Comment by smsohan** [comment]
closing in favor of https://github.com/smsohan/MvcMailer/pull/125

**Comment by shanselman** [comment]
With all due respect, there's no need for a new branch. Take a look at the changes that I made. This all builds from the same source.

I didn't change anything I only added a new build artifact.  

On Feb 11, 2014, at 10:31 PM, SM Sohan notifications@github.com wrote:

@shanselman thanks for this. I really appreciate it. I've created a new branch for vs2013, please open a PR against that branch. That way we can keep the master as is while release a new version for 2013. Will trigger a build tonight.

**Pull request closed without merging**
